// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmchlpzrhkneqhcjpwvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtY2hscHpyaGtuZXFoY2pwd3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDkwOTQsImV4cCI6MjA2OTcyNTA5NH0.HiOc3Zcvgh2_I538C0CIBKNgGPbFiAWNyWBRlNuhxQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});