
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmchlpzrhkneqhcjpwvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtY2hscHpyaGtuZXFoY2pwd3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDkwOTQsImV4cCI6MjA2OTcyNTA5NH0.HiOc3Zcvgh2_I538C0CIBKNgGPbFiAWNyWBRlNuhxQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// --- Global Realtime subscription on all public tables ---
let reloadTimeout: number | undefined;

function scheduleSoftRefresh() {
  if (typeof window === 'undefined') return;
  if (reloadTimeout) return; // throttle: une seule actualisation rapprochée
  reloadTimeout = window.setTimeout(() => {
    reloadTimeout = undefined;
    console.log('[Realtime] Changement détecté – rafraîchissement de l’interface');
    window.location.reload();
  }, 800);
}

try {
  const channel = supabase
    .channel('realtime-public-all')
    .on(
      'postgres_changes',
      { event: '*', schema: 'public' },
      (payload: any) => {
        // Logs utiles au débogage
        console.log(
          `[Realtime] ${payload?.eventType || 'event'} sur ${payload?.schema || 'public'}.${payload?.table || '?'}`,
          payload
        );

        // Diffuser un CustomEvent pour des abonnements fins éventuels
        if (typeof window !== 'undefined') {
          window.dispatchEvent(new CustomEvent('supabase:realtime-change', { detail: payload }));
        }

        // Rafraîchir l’UI pour refléter les nouvelles données
        scheduleSoftRefresh();
      }
    )
    .subscribe((status) => {
      console.log('[Realtime] Canal statut:', status);
    });
} catch (e) {
  console.warn('[Realtime] Impossible d’initialiser la souscription Realtime', e);
}
